version: "3.8"

services:
  database:
    image: mongo
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database:27017/

  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://root:example@database:27017/

  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - 3000:3000
    environment:
      - BACKEND_URL=http://backend:5000/api

volumes:
  mongo-data:
