version: "3.8"

services:
  database1:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data-1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  # database2:
  #   image: mongo
  #   restart: unless-stopped
  #   volumes:
  #     - ./mongo-data-2:/data/db
  #   environment:
  #     MONGO_INITDB_ROOT_USERNAME: root
  #     MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express1:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database1:27017/

  # mongo-express2:
  #   image: mongo-express
  #   restart: unless-stopped
  #   ports:
  #     - 8082:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example
  #     ME_CONFIG_MONGODB_URL: mongodb://root:example@database2:27017/

  backend1:
    build: ./backend
    restart: unless-stopped
    ports:
      - 5001:5000
      - 5998:5999
    environment:
      SERVER_ID: 1
      OTHER_SERVERS: 2
      SERVER_BASE_URL: http://backend{}:5000/api
      MONGO_URI: mongodb://root:example@database1:27017/

  # backend2:
  #   build: ./backend
  #   restart: unless-stopped
  #   ports:
  #     - 5002:5000
  #   environment:
  #     SERVER_ID: 2
  #     OTHER_SERVERS: 1
  #     SERVER_BASE_URL: http://backend{}:5000/api
  #     MONGO_URI: mongodb://root:example@database2:27017/

  frontend1:
    build:
      context: ./frontend
      args:
        REACT_APP_BACKEND_URL: http://localhost:5001/api
    depends_on:
      - backend1
    ports:
      - 3001:3000

  # frontend2:
  #   build:
  #     context: ./frontend
  #     args:
  #       REACT_APP_BACKEND_URL: http://localhost:5002/api
  #   depends_on:
  #     - backend2
  #   ports:
  #     - 3002:3000

volumes:
  mongo-data:
