version: "3.8"

services:
  database1:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data-1:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  database2:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data-2:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  database3:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data-3:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  database4:
    image: mongo
    restart: unless-stopped
    volumes:
      - ./mongo-data-4:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express1:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database1:27017/

  mongo-express2:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8082:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database2:27017/

  mongo-express3:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8083:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database3:27017/

  mongo-express4:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8084:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@database4:27017/

  backend1:
    build: ./backend
    restart: on-failure
    ports:
      - 5001:5000
      - 7001:7000
    environment:
      SERVER_ID: 1
      OTHER_SERVERS: 2,3,4
      MONGO_URI: mongodb://root:example@database1:27017/

  backend2:
    build: ./backend
    restart: on-failure
    ports:
      - 5002:5000
      - 7002:7000
    environment:
      SERVER_ID: 2
      OTHER_SERVERS: 1,3,4
      MONGO_URI: mongodb://root:example@database2:27017/

  backend3:
    build: ./backend
    restart: on-failure
    ports:
      - 5003:5000
      - 7003:7000
    environment:
      SERVER_ID: 3
      OTHER_SERVERS: 1,2,4
      MONGO_URI: mongodb://root:example@database3:27017/

  backend4:
    build: ./backend
    restart: on-failure
    ports:
      - 5004:5000
      - 7004:7000
    environment:
      SERVER_ID: 4
      OTHER_SERVERS: 1,2,3
      MONGO_URI: mongodb://root:example@database4:27017/

  proxy1:
    build: ./proxy
    restart: unless-stopped
    ports:
      - 4001:4000
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - database1
      - database2
      - database3
      - database4
  proxy2:
    build: ./proxy
    restart: unless-stopped
    ports:
      - 4002:4000
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - database1
      - database2
      - database3
      - database4
  proxy3:
    build: ./proxy
    restart: unless-stopped
    ports:
      - 4003:4000
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - database1
      - database2
      - database3
      - database4
  proxy4:
    build: ./proxy
    restart: unless-stopped
    ports:
      - 4004:4000
    depends_on:
      - backend1
      - backend2
      - backend3
      - backend4
      - database1
      - database2
      - database3
      - database4
  frontend1:
    build:
      context: ./frontend
      args:
        REACT_APP_PROXY_URL_1: https://328995431ca3.ngrok.app/api
        REACT_APP_PROXY_URL_2: https://0c37759af7fa.ngrok.app/api
        REACT_APP_PROXY_URL_3: https://cd96aaef4413.ngrok.app/api
        REACT_APP_PROXY_URL_4: https://1ebe22b4bb37.ngrok.app/api

    depends_on:
      - backend1
    ports:
      - 3001:3000
